# Discord webhook
webhook-url: "webhook url"

# Přístup k db
database:
  name: "jmeno"
  user: "uzivatel"
  password: "heslo"
  port: 3306

# LiteBans db
litebans-database:
  host: "localhost"
  port: 3306
  name: "litebans"
  user: "root"
  password: "heslo"


permissions:
  list: "ketchupstaff.cmd.list"
  reset: "ketchupstaff.cmd.reset"
  checkmsg: "ketchupstaff.cmd.checkmsg"
  playtime: "ketchupstaff.playtime"
  stats: "ketchupstaff.stats"

messages:
  nly-player: "&cTento příkaz lze použít pouze jako hráč."
  usage-main: "&ePoužití: /ketchupstaff <list/reset/checkmsg/playtime>"
  unknown-subcommand: "&cNeznámý podpříkaz."
  cmd-reset: "&cDatabáze byla resetována."
  no-permission: "&cNemáš oprávnění."

  # /ketchupstaff checkmsg
  message-check: "&eHelper &6%player% &eposlal &b%count% &ezpráv za danou dobu."
  usage-checkmsg: "&cPoužití: /ketchupstaff checkmsg <nick> <čas>"

  # /ketchupstaff list
  cmd-list: "&aSeznam všech helperů a jejich playtime:"
  playtime-format: "&7%player%: &e%time%"

  # /ketchupstaff playtime
  usage-playtime: "&ePoužití: /ketchupstaff playtime <nick>"
  playtime-show: "&eHelper &b%player% &eodehrál &b%time%."
  playtime-not-found: "&cNelze načíst playtime pro helpera &4%player%&c."

  # /ketchupstaff stats
  usage-stats: "&ePoužití: /ketchupstaff stats <nick> [ban|mute|warn|kick]"
  stats-invalid-type: "&cNeplatný typ trestu. Použij ban/mute/warn/kick."
  stats-single: "&e%player% udělil &b%count% &e%type%(ů)."
  stats-header: "&eStatistiky trestů od &b%player%&e:"
  stats-bans: "&6Bany: &b%count%"
  stats-mutes: "&6Muty: &b%count%"
  stats-warnings: "&6Varování: &b%count%"
  stats-kicks: "&6Kicky: &b%count%"

helper-groups:
  - helper
  - zk.helper
  - el.helper

settings:
  afk-detection-minutes: 10
